### ISSUE TITLE
Uncaught TypeError: Cannot read property '__attachedInstances' of undefined

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-overlay#117]
https://cdn-origin.vaadin.com/vaadin-overlay/3.2.0-alpha1/demo/

Chrome/Windows

![image](https://user-images.githubusercontent.com/6059356/44512680-07d4fd80-a6c4-11e8-9852-a8ba1a84529a.png)

**Comment by platosha** [comment]
fixed in 47674b9247905b57f80229a89b1fe05a785f29ee
