### ISSUE TITLE
The 'Modeless (Non-Modal) Overlay' example doesn't work

### ISSUE THREAD

**Issue by limonte** [vaadin/vaadin-overlay#118]
https://cdn-origin.vaadin.com/vaadin-overlay/3.2.0-alpha1/demo/

Steps to reproduce: Click the 'Toggle the modeless overlay' button

Expected: a modeless overlay is shown

Actual: nothing happens

**Comment by platosha** [comment]
Now works in v3.2.0-alpha2. Fixed probably in 47674b9247905b57f80229a89b1fe05a785f29ee.
