### ISSUE TITLE
Shady DOM custom style "leak" due to dynamic creation of overlay content

### ISSUE THREAD

**Issue by attilapuskas** [vaadin/vaadin-overlay#123]
Whenever a _vaadin-overlay_ is used for example via a _vaadin-combo-box-dropdown_ and ShadyCSS is used then a new `vaadin-overlay-content-${overlayContentCounter}` is created even if the cssText is the same every time.

When using for example twenty combo-box in a form inside a dialog then it can make the dialog opening very slow inside IE 11. Also the `<head>` become bigger and bigger every time such dialog is opened because of the newly created elements with the same style.

Isn't it possible to use a _cache_ based on the cssText to avoid creating such elements?

**Comment by platosha** [comment]
Yes, should be possible. Good idea.

**Comment by attilapuskas** [comment]
I imagined something like that (works like a charm):

![image](https://user-images.githubusercontent.com/23697276/53245376-d5757e80-36ad-11e9-9bd4-3fc76a8fde13.png)

I won't create a PR as I am not familiar with the tests of the vaadin-overlay so it might take a while but would be really nice if you can create a quick-fix for that in the near future because defining a custom element (including a new scoped style) for every vaadin-combo-box makes the already slow IE even worse.

For example we are using Vaadin VWindow-s for editing certain records with combo boxes in it so opening some of these forms could easily flood the <head> with additional style elements.

**Comment by attilapuskas** [comment]
Cool, thank you!
