### ISSUE TITLE
vaadin-overlay v3.2.7 -> v3.2.11 does not work together with the vaadin-dialog

### ISSUE THREAD

**Issue by brp-benjamin** [vaadin/vaadin-overlay#152]
Since vaadin 12.0.6 there is a bug where opening multiple modals makes the ui unresponsive due to pointer-event swallowing from the vaadin-overlay. I have tracked this down to changes in vaadin-overlay v3.2.7

See corresponding bug in vaadin-dialog-flow:

https://github.com/vaadin/vaadin-dialog-flow/issues/121

**Comment by web-padawan** [comment]
Confirmed the linked dialog issue with the web components:
https://glitch.com/edit/#!/spot-schooner?path=index.html:18:0

I will investigate what exact change caused this.
