### ISSUE TITLE
Add positioning and alignment properties

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-overlay#155]
Introduce new properties that could eliminate some of the redundant overlay positioning/alignment logic from components that use the overlay.

Some of the suggested properties are inspired by [iron-fit-behavior](https://www.webcomponents.org/element/@polymer/iron-fit-behavior/behaviors/IronFitBehavior)

`positionTarget`: The element relative to which the overlay is positioned
`horizontalAlign`: The orientation against which to align the overlay horizontally relative to the positionTarget. Possible values are "start", "end". This should respect rtl.
`verticalAlign`: The orientation against which to align the overlay vertically relative to the positionTarget. Possible values are "top", "bottom".
`noHorizontalOverlap`: Will position the overlay around the positionTarget without overlapping it horizontally.
`noVerticalOverlap`: Will position the overlay around the positionTarget without overlapping it vertically.
~`useFullscreen`: The overlay should snap to fullscreen mode on small viewport~

| Overlay of   |      positionTarget      |  horizontalAlign |  verticalAlign |  noHorizontalOverlap | noVerticalOverlap |
|:----------|:-------------|:------|:------|:------|:-----|
| DatePicker |  The internal text-field | start | top | false | true |
| ComboBox |  The internal text-field | start | top | false | true |
| MenuBar |  The active root level button | start | top | false | true |
| ContextMenu |  The listenOn element  |  |  |  |  |
| ContextMenu sub-menu | Parent item | end | top | true | false |
| Dialog | | | | | |
| Select | The internal text-field | start | top | false | false |

Overlay should flip to the other side both horizontally or vertically when there is not enough space to fit the full overlay content without squeezing and the other side has more space.

**Comment by pekam** [comment]
[Proto branch](https://github.com/vaadin/vaadin-overlay/tree/proto-alignment-api)

**Comment by web-padawan** [comment]
Re-implemented the prototype also in [lit-element](https://github.com/web-padawan/lit-combo-box/blob/master/src/lit-positioned-overlay.ts).
