### ISSUE TITLE
IE11 shadydom null reference

### ISSUE THREAD

**Issue by srijken** [vaadin/vaadin-overlay#156]
When running in ShadyDOM (in Internet Explorer 11) there's an error:
`Unable to get property 'appendChild' of undefined or null reference`

Problem doesn't appear to be browser specific, other than ShadyDOM vs ShadowDOM

I've traced this to: 
https://github.com/vaadin/vaadin-overlay/blob/v3.2.12/src/vaadin-overlay.html#L796
Here the shadowRoot is attached

and:
https://github.com/vaadin/vaadin-overlay/blob/v3.2.12/src/vaadin-overlay.html#L827
Here the content property is overwritten by a node without shadowRoot

**Comment by Haprog** [comment]
@srijken I can't reproduce this issue with current `master` branch or version `v3.2.12`. Overlay demos seem to work fine on IE11 in Win 10 when running with `polymer serve`.

Can you post a code example on how to reproduce this and more details about your environment (Windows version, more specific IE version)?

**Comment by srijken** [comment]
Repro: https://github.com/srijken/vaadin-select-repro

The problem is triggered by the dom-if around the element that contains vaadin-select

**Comment by Haprog** [comment]
@srijken Thanks. I didn't have time to take a look at your repo yet and I'm heading for 3 week vacation right now, but someone else from the team will probably take a look.

**Comment by Haprog** [comment]
I'm back from vacation. Will take a new look probably tomorrow.

**Comment by Haprog** [comment]
Thanks for the repro repo! I can also reproduce it now. I also just noticed the discussion and progress in the PR #157. I'll comment there.
