### ISSUE TITLE
UI get locked when opening two dialogs in direct sequence

### ISSUE THREAD

**Issue by brp-jimmy** [vaadin/vaadin-overlay#158]
**Description** 
Even after the fix that came after the discussion in issue https://github.com/vaadin/vaadin-dialog-flow/issues/121 - fixed in #153 - we still have problems with the UI locking when two dialogs are opened in direct sequence.

Unfortunatley I do not have code to share that reproduces this error. But we have a more complex dialog that in some cases opens a message dialog to instruct the user to directly do something. 

So in the big dialog I have added an openedChangeListener that fires up the second dialog. And it is done in the java code using Vaadin flow.

Pseudo code:
```
Dialog firstDialog = new Dialog();
firstDialog.init() // Do some stuff and sets up listeners and data bindings
firstDialog.addOpenedChangeListener(event -> if (actionNeedsToBeTaken()) showInfoDialog())
firstDialog.open()
```

What happens then is that in the flow component Dialog everything seems fine but the overlay in the DOM comes in the wrong order. The overlay with the first nodeId is below the second overlay in the DOM tree.

The javascript code for the overlay is called in the wrong order. My thinking is that the rendering of the first dialog takes more time and therefore is called before.

Do you have an idea what the issue can be? Let me know if you can come up with any other information that I can share that can help.

**Versions** 
Vaadin 13.0.8 
Vaadin-overlay 3.2.12
Chrome Version 75.0.3770.100

**Comment by tomivirkki** [comment]
Hi, tried to reproduce the case by following the provided pseudo code. Here's what I ended up with:

```java
@Route("")
public class MainView extends VerticalLayout {

    public MainView() {

        Dialog infoDialog = new Dialog();
        infoDialog.add("Info");

        Dialog firstDialog = new Dialog();
        firstDialog.add("First");
        firstDialog.addOpenedChangeListener(event -> {
            infoDialog.open();
        });

        Button button = new Button("Open", event -> firstDialog.open());
        add(button);

    }
}
```
Should some additional wiring be done? I couldn't make it happen with this snippet alone.

**Comment by brp-jimmy** [comment]
Thanks for looking into it. But no, your example will not reproduce the error as you have noticed. We have a quite complex dialog with a bunch of listeners and some data binding to input fields. The problem with UI locking happens 100% of the time for us but I cannot manage to pinpoint what in our code that causes the error which makes it hard to error search. I cannot post that large part of our code base either.

My hope is that you have seen something similar before or can figure out what can cause the behaviour of the form dialog being called in one order but the overlay is added to the DOM in another, causing the lock up.

**Comment by Deepercreeper** [comment]
Hey, I just got the same problem and have a very simple example to reproduce (I think):
```
@Route("")
public class MainView extends VerticalLayout {
    public MainView() {
        add(new Button("Test", event -> test()));
    }

    private void test() {
        dialog = new Dialog();
        dialog.setWidth("100px");
        dialog.add(new Button("Dialog", event -> dialog()));
        dialog.open();
    }

    private void dialog() {
        dialog = new Dialog();
        dialog.setWidth("100px");
        TextField field = new TextField();
        field.setWidthFull();
        dialog.add(field);
        dialog.open();
    }
}
```

The "I think" is because I didn't create a new project but instead just added the test button in an existing project and the bug appeared. Please respond, if this is not reproducible this way.

It really seems to be important, that the second dialog is opened using a listener or a widget inside the first one.

Edit: An important note is that the textfield works properly as soon as the top most dialog lost his focus once.

**Comment by web-padawan** [comment]
@Deepercreeper can you please specify what Vaadin version are you using?

**Comment by Deepercreeper** [comment]
@web-padawan sure. I'm using vaadin-core 14.1.2 including vaadin-dialog-flow 2.0.1.

**Comment by mas4ivv** [comment]
We have the same problem, so I tried to reproduce this with the example from Deepercreeper. I finally found a way - and it seems like it is somehow connected to the TextArea:

`@Route("")
public class MainView extends VerticalLayout {

    public MainView() {
        add(new Button("Test", event -> test()));
    }

    private void test() {
        Dialog dialog = new Dialog();
        dialog.setCloseOnOutsideClick(false);
       dialog.setWidth("100px");
        dialog.add(new Button("Dialog", event -> dialog()));
        dialog.open();
        dialog();
    }

    private void dialog() {
        Dialog dialog = new Dialog();
        dialog.setCloseOnOutsideClick(false);
        dialog.setWidth("100px");
        TextArea field = new TextArea();
        field.setWidthFull();
        dialog.add(field);
        dialog.open();
    }
}`

I am opening a second dialog directly after opening the first one (it won't reproduce if I click the button on the first dialog). Now I am unable to use the text area. When using escape to close the top dialog and opening it again using the button on the first dialog everything is fine. If I change the TextArea into a TextField, everything works as expected.
We are using 14.1.16 in our app, this demo was built using 14.0.11. The dialogs in our app that cause this problem all include a TextArea.

**Comment by tomivirkki** [comment]
Confirmed the issue with https://github.com/vaadin/vaadin-overlay/issues/158#issuecomment-586124066

**Comment by Haprog** [comment]
Here's a minimal client side only reproduction of this issue (without using Flow). This works at least in Chrome in the same way as the above Java API snippet.

Save this as `index.html` in an empty directory:
```html
<!doctype html>
<html>
  <head>
    <script type="module">
      import '@vaadin/vaadin-dialog';
      import '@vaadin/vaadin-text-field/vaadin-text-area.js';
    </script>
  </head>
  <body>
    <button onclick="window.dialog1.opened = true; window.dialog2.opened = true">Test</button>
    <vaadin-dialog id="dialog1" no-close-on-outside-click>
      <template><button onclick="window.dialog2.opened = true">Dialog</button></template>
    </vaadin-dialog>
    <vaadin-dialog id="dialog2" no-close-on-outside-click>
      <template><vaadin-text-area></vaadin-text-area></template>
    </vaadin-dialog>
  </body>
</html>
```

Run this in the directory:
```
npm i -g polymer-cli
npm init -y
npm i --save @vaadin/vaadin-dialog @vaadin/vaadin-text-field
polymer serve
```

Navigate to http://127.0.0.1:8081/

I also tried using renderer API instead of `<template>` for the dialogs and creating the dialogs on the fly when clicking the button (more similar to how the Flow API does it), but the behaviour was the same on all cases so no difference there.
