### ISSUE TITLE
Firefox capture screen is affected by pointer-events: none on body

### ISSUE THREAD

**Issue by vincenzocalabrese** [vaadin/vaadin-overlay#165]
Hello,
when the dialog is opened is not possibile capture the screen until the dialog is closed.
I've used the Firefox capture screen, the capture object is behind the dialog object.

Vincenzo

**Comment by web-padawan** [comment]
It turns out `pointer-events: none` also causes other undesirable side-effects. 

For instance, the element can't be selected with Web Inspector: https://bugzilla.mozilla.org/show_bug.cgi?id=745489 

So let me consider this a browser issue and close as won't fix.
