### ISSUE TITLE
Closing multiple dialogs and pointer-events

### ISSUE THREAD

**Issue by rokkolesa** [vaadin/vaadin-overlay#176]
- Description of the bug
Whenever multiple `Dialog` instances are rendered (> 2) and the top two are closed at the same time, the underlying `Dialog` cannot be interacted with - it still has `pointer-events: none`.

- Minimal reproducible example
As an example I downloaded the `Simple App` starter, added a `View` (`extends HorizontalLayout`, the same as other `View`s in the starter)  and in it's constructor written the following code:
```java
add(new Button("Open Dialog 1", e -> {
    final Dialog dialog1 = new Dialog();
    dialog1.setCloseOnOutsideClick(false);
    dialog1.add(new Label("This is Dialog 1"));
    dialog1.add(new Button("Open Dialog 2", e1 -> {
        final Dialog dialog2 = new Dialog();
        dialog2.setCloseOnOutsideClick(false);
        dialog2.add(new Text("This is Dialog 2"));
        dialog2.add(new Button("Open Dialog 3", e2 -> {
            final Dialog dialog3 = new Dialog();
            dialog3.setCloseOnOutsideClick(false);
            dialog3.add(new Text("This is Dialog 3"));
            dialog3.add(new Button("Close Dialogs 2 and 3", e3 -> {
                dialog3.close();
                dialog2.close();
            }));
            dialog3.open();
        }));
        dialog2.open();
    }));
    dialog1.open();
}));
setSizeFull();
setJustifyContentMode(JustifyContentMode.CENTER);
setAlignItems(Alignment.CENTER);
```

The `setCloseOnOutsideClick(false)` is set so the issue is more apparent.

The first two `Dialog`s open and close fine on their own, but when clicking on the button that closes `Dialog`s 2 and 3, the first `Dialog` still has `pointer-events: none` and cannot be interacted with.

- Expected behavior
After closing multiple `Dialog`s at once the top `Dialog` should not have `pointer-events: none`.

- Actual behavior
After closing multiple `Dialog`s at once the top `Dialog` still has `pointer-events: none` and cannot be interacted with. Closing it with outside click or ESC still work as expected.

- Temporary fix
The only fix right now is to downgrade the `vaadin-overlay` package to `3.2.18`. On that version everything works fine.

- Versions:
    - Vaadin `14.1.21` / Flow version `2.1.6`
    - Java `8`, `11`
    - OS version: `macOS Catalina 10.15.3` 
    - Browsers:
        - Chrome `80.0.3987.149`
        - Firefox `74.0`
        - Safari `13.0.5`
        - Edge `80.0.361.69`

**Comment by alump** [comment]
I have this same issue, and here is my test app:

```
public class MainView extends Div {

    public static class MyDialog extends Dialog {
        public MyDialog(Runnable closeMeAlso) {
            setCloseOnOutsideClick(false);

            Button open = new Button("Open", e -> new MyDialog(() -> this.close()).open());
            Button close = new Button("Close", e -> this.close());
            Button close2 = new Button("Close", e -> {
                this.close();
                closeMeAlso.run();
            });

            HorizontalLayout layout = new HorizontalLayout(open, close, close2);
            close2.setVisible(closeMeAlso != null);
            close.setVisible(!close2.isVisible());
            add(layout);
        }
    }

    public MainView() {

        Html guide = new Html("<ul><li>Click <b>Open</b></li>"
                + "<li>Click <b>Open</b> in the dialog</li>"
                + "<li>Click <b>Open</b> in the dialog again</li>"
                + "<li>Click <b>Close</b> in the dialog</li>"
                + "<li>User can't interact with the dialog</li>"
                + "</ul>");

        setSizeFull();

        Button open = new Button("Open", e -> new MyDialog(null).open());

        VerticalLayout initialLayout = new VerticalLayout();
        initialLayout.add(guide, open);
        add(initialLayout);
    }
}
```

**Comment by alump** [comment]
Also verified that the issue goes away if vaadin-overlay is forced to 3.2.18, so this is regression.

Workaround: Adding following annotation to one of your UI classes
`@NpmPackage(value = "@vaadin/vaadin-overlay", version = "3.2.18")`

**Comment by ratzalex** [comment]
We have the same issue:

Versions:
- Vaadin 14.1.28 with vaadin-overlay 3.2.19
- AdoptOpenJDK Java 11.0.6
- Windows 10 1909
- Browsers:
  - Chrome: 83.0.4103.61
  - Firefox 76.0.1

**Comment by web-padawan** [comment]
The regression was introduced by https://github.com/vaadin/vaadin-overlay/commit/78a01104bad237d1d2a8d641e3e9f7558881bd86

We have to figure out what change caused it.

**Comment by rokkolesa** [comment]
> Also verified that the issue goes away if vaadin-overlay is forced to 3.2.18, so this is regression.
> 
> Workaround: Adding following annotation to one of your UI classes
> `@NpmPackage(value = "@vaadin/vaadin-overlay", version = "3.2.18")`

For vaadin `14.2.0` the regressed version is `3.3.1` and the non-regressed is `3.3.0`. I tested it with `npm` and it works fine.

It seems though that this workaround does not work anymore for vaadin version `14.2.0` with `pnpm` enabled.

**Comment by web-padawan** [comment]
> this workaround does not work anymore for vaadin version 14.2.0 with pnpm enabled.

With pnpm we enforce components versions to those provided by [platform](https://github.com/vaadin/platform). It is still possible to override but only if a version you provide in `package.json` is newer. 

As soon this issue is fixed and a patch release for `vaadin-overlay` published, you will be able to override it again.

**Comment by rokkolesa** [comment]
I noticed that version `3.4.0` is already released and tried to override the version to it:

```java
@NpmPackage(
        value = "@vaadin/vaadin-overlay",
        version = "3.4.0"
)
```

The generated lockfile is the same - with `vaadin-overlay` version `3.3.1`. I noticed that this change causes a change in `package.json` - `dependencies."@vaadin/vaadin-overlay"` and `vaadin.dependencies."@vaadin/vaadin-overlay"` change to `3.4.0` (`vaadin.hash` also changes, but that is expected and correct).

If i manually change the version in `vaadin.dependencies."@vaadin/vaadin-overlay"` back to `3.3.1` and leave the  `dependencies."@vaadin/vaadin-overlay"` on `3.4.0` it seems that lockfile indeed changes to `3.4.0` and this version is also visible in `node_modules/@vaadin/vaadin-overlay`.. however, version `3.3.1` is still bundled and the overridden version is nowhere to be seen in the bundle. Even if I run in devmode with `webpack-dev-server`, the `3.3.1` is served instead of `3.4.0`.

I also checked if `3.4.0` works as expected with `npm` and it indeed does - the double dialog closing works fine.

**Comment by web-padawan** [comment]
When the issue is fixed, we should make the following patch releases:

- `3.5.x`
- `3.4.x`
- `3.3.x`

PS: in order to use overriding with `pnpm` and make sure it works properly, you need to:

1. update `vaadin-overlay` version in `package.json`
2. delete `node_modules` and `pnpm-lock.yaml`
3. rebuild project to make sure it installs dependencies

This should make sure you don't get any nested duplicate versions.
