### ISSUE TITLE
Allow the user configure when he wants the overlay being moved to body

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#21]
There are use cases when the user prefers not moving the overlay to the body and define content, and style it in the natural wc way. A flag should be enough.

Related with https://github.com/vaadin/vaadin-dialog/issues/11

**Comment by tomivirkki** [comment]
We don’t have plans to support 2 different modes/API’s in `<vaadin-overlay>` (or our elements that use it) simultaneously. Related: https://github.com/vaadin/vaadin-dialog/issues/11#issuecomment-327418606
