### ISSUE TITLE
Set focus on open, and Restore focus on close.

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#23]
Focus is not restored when closing the overlay, last active element in the document should be focused

**Comment by manolo** [comment]
Reported as well during UX Testing 

https://github.com/vaadin/vaadin-material-styles/issues/52

**Comment by tomivirkki** [comment]
This should only affect overlay's when focusTrap is on

**Comment by web-padawan** [comment]
I don't see why was this moved to `in review unscoped`, there does not seem to be any PR handling this anywhere. So moving it back to the Backlog now.
