### ISSUE TITLE
Add transitions

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#36]
Related to https://github.com/vaadin/vaadin-date-picker/issues/153 and https://github.com/vaadin/vaadin-combo-box/issues/65

**Comment by tomivirkki** [comment]
This is implemented separately in elements using the overlay

**Comment by jouni** [comment]
@tomivirkki, are you saying we should implement this separately in each element? I would think this is a common feature that could be inherited by all overlays. I would like to use some transitions for most overlays.

**Comment by tomivirkki** [comment]
https://github.com/vaadin/vaadin-date-picker/issues/153#issuecomment-336029437 ?

**Comment by jouni** [comment]
Yeah, right. I might want to change my previous statement – I think it would be possible to achieve the desired results with the generic vaadin-overlay animation/transition feature. For example, have a separate animation for the date selection and delay the overlay closing animation until it’s finished.
