### ISSUE TITLE
Consider a flag to know that the overlay is the last in the stack

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#43]
When opening nested overlays e.g a vaadin-combo-box inside a vaadin-dialog we might need a way to know if the vaadin-dialog is the last in the stack to prevent closing it on escape or outside clicks.

**Comment by jouni** [comment]
The element that handles the Esc-keypress should stop the propagation of that event once it has handled it (i.e. closed its overlay). It should not reach the parent elements then.

Same for outside clicks – the element should have a modality curtain that blocks clicks outside it and stop the click event from propagating after that also.
