### ISSUE TITLE
Fix focus trap behavior

### ISSUE THREAD

**Issue by tomivirkki** [vaadin/vaadin-overlay#45]
The current focus rotating behaviour doesn't take into account focusable elements inside shadow roots of child elements.

Drop the current focus trap implementation, and instead:

- Add a custom <kbd>Tab</kbd> (<kbd>Shift</kbd>+<kbd>Tab</kbd>) keydown listener for the dialog, preventing default action;
- On every keydown, query for all focusable elements from the dialog contents. Use recursive walk to collect elements from inside shadow roots:
  - Add `iron-overlay-behaviour` dependency and use `Polymer.IronFocusablesHelper.getTabbableNodes(node)`, see https://github.com/PolymerElements/iron-overlay-behavior/blob/master/iron-focusables-helper.html ;
- Find the next (previous in case of <kbd>Shift</kbd>+<kbd>Tab</kbd>) focusable from the query results and do the `focus()` jump in the keydown listener;
- Add a focus trap demo with some fields inside a web component;
- Add tests.

This should result in the focus rotating natively inside a "focus trapping" overlay

**Comment by platosha** [comment]
This implies making overlays focusable and introducing a focused state on the overlay. Requires some more thinking IMO:
- Having overlays focusable might not be applicable on every use case. Does notification overlay need this? Dropdown overlay?
- According to accessibility best practices, the focused state must be styled.
- Once the overlay is focused, if the overlay has scrollable content, I would expect keyboard to manipulate scrolling of the content. Maybe focusing `[part="overlay"]`, where the we have `overlay: auto;` style, would help for some use cases. But that would not work for `<vaadin-combo-box>`, which uses a separate scrollable div.

At this point, it seems for me it’s better not to *redesign* the focus behaviour of all the overlays at this point, as this might bring too many consequences.

I would rather fix the focusable discovery code to take shadow roots into account. This requires a bit of verbose code, maybe, but on the other hand would not bring new features or states to all the overlays.

**Comment by tomivirkki** [comment]
If focusing the focus trapping overlay is a problem (?), then sure. The current manual focus looping logic is broken however -> rely on native tabbing behaviour inside the overlay and on overlay focusout refocus the element that's assumed to be the first/last focusable.
