### ISSUE TITLE
Propagate `theme` attribute to the actual visible overlay element

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-overlay#48]
We are pretty much in the process of adopting the `theme` property as a standard property for all elements. And sometimes overlays need customized theming as well. It would be really helpful if the main overlay element, which the developer is responsible for creating/manipulating, would propagate the `theme` attribute to the teleported overlay container element.

In the case of `vaadin-notification`, the attribute should end up in the `vaadin-notification-card` element.

**Comment by manolo** [comment]
Note that this should be done in each element using the overlay.  The `vaadin-overlay` itself is not accessible by the user for theming it.

The user would write:

```
  <vaadin-notification theme="dark"></vaadin-notification>

  <vaadin-dialog theme="right"></vaadin-dialog>

  <vaadin-context-menu theme="foo"></vaadin-context-menu>
```

**Comment by platosha** [comment]
Duplicate of vaadin/vaadin-themable-mixin#12, let us continue there.
