### ISSUE TITLE
overlay should implement iron-resizable-behavior 

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#61]
When overlay contains resizable elements like form-layout they need to be notified when the overlay opens.

**Comment by tomivirkki** [comment]
Can you provide an example where this is an issue? Hopefully an isolated one where we can reproduce/analyze it.

**Comment by web-padawan** [comment]
BTW below is the example of how the issue with such a short description can be handled 😄 
https://github.com/TryGhost/Casper/issues/286#issuecomment-281907266

**Comment by web-padawan** [comment]
> Can you provide an example where this is an issue? Hopefully an isolated one where we can reproduce/analyze it.

There has not been any complaint so far. I guess we can close this issue for now.
Let's reopen it later if we realise the form-layout is not working properly.
