### ISSUE TITLE
focus-trap fails when shift-tabing

### ISSUE THREAD

**Issue by manolo** [vaadin/vaadin-overlay#66]
Open the `vaadin-dialog` 'Show dialog' demo. Push tab several times and focus loops correctly on buttons, then shift-tab, a console error is displayed, and focus escapes from the dialog to body.

Tested in v2.0.5

**Comment by manolo** [comment]
Fixing this, should also fix https://github.com/vaadin/beverage-starter-flow/issues/181

**Comment by web-padawan** [comment]
The problem especially occurs because of focusing underlying native `button` in the `vaadin-button` component (works nice for standalone native buttons).
