### ISSUE TITLE
Overlay should not automatically focus the first focusable element inside it

### ISSUE THREAD

**Issue by jouni** [vaadin/vaadin-overlay#68]
When I create a `<vaadin-dialog>` with a text field as the first component inside it, I don’t always want that field to get focused automatically when the dialog is opened.

Focusing the text field causes the on-screen keyboard to pop-up at least on Android, which in many cases is unexpected and unwanted by the end user.

Moving the focus to some other element than the overlay itself when it’s opened should be an opt-in decision by the developer, not mandated by the overlay.

**Comment by platosha** [comment]
Let us consider making the overlay part focusable, and focusing it by default. That would fix the issue, and also give:

- Accessibility benefits: when the overlay opens, the content will be announced, not only the first focusable
- Focus on the scrollable part allows scrolling with keyboard, which is nice for static content
- After uses presses `<tab>`, first focusable will naturally focus. This is similar to how focus works in the document, which is nice.
- Potentially allows modal overlay to implement focus trapping without intrusive shadow roots inspection.

**Comment by jouni** [comment]
I suppose this can be considered as a breaking change from the perspective of the utilizing components, such as vaadin-dialog and vaadin-dropdown-menu. Also, dropdown-menu would probably still want to focus the first focusable element instead (usually a vaadin-list-box).

If that’s the case, then I think we should try to get this fix in during the beta period of those utilizing components, so we don’t have to postpone the change to the next major versions.

**Comment by manolo** [comment]
One option is not to focus when it's a touch device, at least this would fix the issue in bakery.
another option is not enable focus-trap in touch devices, does focus trap make sense in mobile?
