### ISSUE TITLE
Overlay cannot be removed from dom after closing the dialog

### ISSUE THREAD

**Issue by ZheSun88** [vaadin/vaadin-overlay#71]
with `vaadin-dialog` 2.0.0-beta3, when the dialog has `lumo` theme on, the `vaadin-dialog-overlay` will not be removed from the dom when close the dialog. and if i remove the theme, everything works.

related discussion on slack https://vaadin.slack.com/archives/C3TGRP4HY/p1522156886000459

**Comment by manolo** [comment]
Seems not being an issue anymore. 
Double checked in polymer and flow demos and cannot reproduce.

**Comment by dinumihnea** [comment]
I reproduced.
This issues is caused by CSS animation delay.
Without animation it works excellent.

Simple animation example to reproduce:
` 
          :host([opening]) {
                animation:  overlay-enter 0.5s;
            }
            @keyframes overlay-enter {
                0% {
                    opacity: 0;
                }
            }
`

**Comment by manolo** [comment]
It might be related to https://github.com/vaadin/vaadin-material-styles/issues/76
